version: '3.4'

services:

  mongo:
    container_name: bookstoredb
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017

  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 5000:80

  ui:
    container_name: catalog_ui
    image: ${DOCKER_REGISTRY-}catalog-ui
    build: 
      context: ../front-end/catalog/.
      dockerfile: Dockerfile
    ports:
      - 3001:80

volumes:
  mongodata:
    external: true
    name: mongodata