version: '3.4'

services:

  mongo:
    container_name: bookstoredb
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - lan-network
    ports:
      - 27018:27017

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      networks:
        - lan-network      
      ports:
        - 8080:8080
      restart: always
      command:
        - start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      volumes:
        - keycloakdata:/opt/keycloak/data/h2

  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - mongo
      - keycloak
    links:
      - mongo
      - keycloak
    networks:
      - lan-network
    ports:
      - 5005:8080

  ui:
    container_name: catalog_ui
    image: ${DOCKER_REGISTRY-}catalog-ui
    build: 
      context: ../front-end/catalog/.
      dockerfile: Dockerfile
    ports:
      - 3000:80

volumes:
  mongodata:
    external: true
    name: mongodata
  keycloakdata:
    external: true
    name: keycloakdata

networks:
  lan-network:
    driver: bridge