services:

  mongo:
    container_name: bookstoredb
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - lan-network
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      networks:
        - lan-network      
      ports:
        - 8080:8080
      restart: always
      command:
        - start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      volumes:
        - keycloakdata:/opt/keycloak/data/h2
      healthcheck:
        test:
          [
            "CMD-SHELL",
            'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
          ]

  catalog:
    container_name: catalog
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      mongo:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    links:
      - mongo
      - keycloak
    networks:
      - lan-network
    ports:
      - 5005:8080
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  ui:
    container_name: catalog_ui
    image: ${DOCKER_REGISTRY-}catalog-ui
    build: 
      context: ../front-end/catalog/.
      dockerfile: Dockerfile
    depends_on:
      catalog:
        condition: service_healthy
    ports:
      - 3000:80

volumes:
  mongodata:
    external: true
    name: mongodata
  keycloakdata:
    external: true
    name: keycloakdata

networks:
  lan-network:
    driver: bridge