version: '3.4'

services:

  mongo:
    container_name: bookstoredb
    image: bookstoredb
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017

  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    ports:
      - "5050:80"

  ui:
    image: ${DOCKER_REGISTRY-}catalog-ui
    build: 
      context: ../../front-end/catalog/.
      dockerfile: Dockerfile
    container_name: catalog_ui
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - catalog
    volumes:
      - '../../front-end/catalog/.:/app'
      - '/app/node_modules'

volumes:
  mongodata:
